org: ishadevops
app: aws-api-lambda-quotes-handler-sg-ce
service: aws-api-lambda-quotes-handler-sg-ce

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  lambdaHashingVersion: "20201221"

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /quotes
          method: GET
      - http:
          path: /cacheQuoteLocally
          method: POST
      - http:
          path: /prot/sgq/auth/bulk
          method: POST
      - http:
          path: /prot/sgq/auth/collate
          method: POST
